import React from 'react';
import { X, Copy, Check, Sparkles, Loader2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown'; // Actually we don't have this in requirements, so we will use simple rendering or native markdown parser if possible. 
// Given the constraints "Use popular libraries... Do not use mock or made-up libraries", I'll write a simple renderer or just display styled text.
// Better: Just display as whitespace-pre-wrap with some basic styling since Gemini returns decent text.
import { ReportType, ReportState } from '../types';

interface ReportModalProps {
  state: ReportState;
  onClose: () => void;
}

export const ReportModal: React.FC<ReportModalProps> = ({ state, onClose }) => {
  const [copied, setCopied] = React.useState(false);

  if (!state.isOpen) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(state.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const getTitle = () => {
    return state.type === ReportType.DAILY_REFLECTION ? "Daily Reflection" : "Weekly Manager Report";
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div 
        className="absolute inset-0 bg-slate-950/80 backdrop-blur-sm"
        onClick={onClose}
      />
      
      <div className="relative w-full max-w-2xl bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl flex flex-col max-h-[85vh] animate-in fade-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-slate-800">
          <div className="flex items-center gap-3">
            <div className={`p-2 rounded-lg ${state.isLoading ? 'bg-indigo-500/10 text-indigo-400' : 'bg-green-500/10 text-green-400'}`}>
              {state.isLoading ? <Sparkles className="w-5 h-5 animate-pulse" /> : <FileCheckIcon />}
            </div>
            <div>
              <h2 className="text-lg font-semibold text-slate-100">{getTitle()}</h2>
              <p className="text-xs text-slate-500">Generated by Gemini AI</p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-slate-800 rounded-lg text-slate-400 hover:text-white transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 custom-scrollbar bg-slate-900/50">
          {state.isLoading ? (
            <div className="flex flex-col items-center justify-center h-64 gap-4 text-slate-500">
              <Loader2 className="w-8 h-8 animate-spin text-indigo-500" />
              <p className="animate-pulse text-sm">Analyzing your timeline...</p>
            </div>
          ) : (
            <div className="prose prose-invert prose-slate max-w-none">
              <div className="whitespace-pre-wrap font-sans text-slate-300 leading-7">
                {state.content}
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        {!state.isLoading && (
          <div className="p-4 border-t border-slate-800 bg-slate-900 rounded-b-2xl flex justify-end gap-3">
             <button 
               onClick={onClose}
               className="px-4 py-2 text-sm font-medium text-slate-400 hover:text-white hover:bg-slate-800 rounded-lg transition-colors"
             >
               Close
             </button>
             <button 
               onClick={handleCopy}
               className="flex items-center gap-2 px-4 py-2 text-sm font-medium bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg transition-colors shadow-lg shadow-indigo-500/20"
             >
               {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
               {copied ? "Copied" : "Copy to Clipboard"}
             </button>
          </div>
        )}
      </div>
    </div>
  );
};

const FileCheckIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
    <polyline points="14 2 14 8 20 8" />
    <path d="m9 15 2 2 4-4" />
  </svg>
)
